apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: chatbot-test-app-7 
  janus-idp.io/tekton: chatbot-test-app-7
  backstage.io/kubernetes-id: chatbot-test-app-7
  backstage.io/kubernetes-namespace: rhdh-app 
  app.kubernetes.io/part-of: chatbot-test-app-7
resources: 
- application-dev.yaml